site_name: I-Form Server Node Deployer
theme: readthedocs
docs_dir: docs
site_dir: site

nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
    - Usage: usage.md
  - Reference:
    - Commands: commands.md
    - Configuration: configuration.md
    - Deployment: deployment.md
    # - Troubleshooting: troubleshooting.md
    # - Changelog: changelog.md
    # - License: license.md