site_name: I-Form Server Node Deployer
theme: readthedocs
docs_dir: docs
site_dir: site

nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
    - Usage: usage.md
  - CLI Usage:
    - Commands: commands.md
    - Configuration: configuration.md
    - Deployment: deployment.md
  - Reference:
    - Documentation:
      - autoignition: src/autoignition.md
      - create_img: src/create_img.md
      - create_disk: src/create_disk.md
    # - FAQ: faq.md
    # - Troubleshooting: troubleshooting.md
    # - Changelog: changelog.md
    # - License: license.md

# markdown_extensions: 
#   - mkdocs-typer

plugins:
  - search
  - mkdocstrings