[build]
publish = "site"
command = """
add-apt-repository ppa:deadsnakes/ppa &&
apt update &&
apt install python3.12 -y &&
pip3 install -q poetry &&
poetry config virtualenvs.in-project true &&
poetry env use python3.12 &&
poetry install -v &&
poetry run build
"""